from enum import Enum
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field


class ValidationStatus(str, Enum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    WARNING = "WARNING"
    CONFLICT = "CONFLICT"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class ValidationSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ValidationResultItem(BaseModel):
    """
    Individual result generated by a validation rule.
    Validation never silently mutates an attribute; it produces this structured result.
    """
    rule: str = Field(description="Name or identifier of the validation rule executed")
    attribute_name: Optional[str] = Field(default=None, description="Target attribute name if rule is attribute-scoped")
    passed: bool = Field(description="True if rule passed without violations")
    status: ValidationStatus = Field(description="Outcome status: PASSED, FAILED, WARNING, CONFLICT, REQUIRES_REVIEW")
    severity: ValidationSeverity = Field(default=ValidationSeverity.LOW, description="Severity level if violation detected")
    message: str = Field(description="Human-readable explanation of the validation finding")
    evidence_ids: List[str] = Field(default_factory=list, description="IDs of evidence supporting this validation result")
    sources: List[str] = Field(default_factory=list, description="Names of documents / sources involved")
    details: Dict[str, Any] = Field(default_factory=dict, description="Supplementary technical context or data")


class CrossSourceComparisonResult(BaseModel):
    """
    Comparison result across multiple sources for a specific attribute.
    """
    attribute_name: str
    is_conflict: bool
    status: ValidationStatus
    severity: ValidationSeverity
    sources: List[Dict[str, Any]] = Field(default_factory=list, description="List of {source_name, value, evidence_id}")
    conflicting_values: List[Any] = Field(default_factory=list)
    message: str
    evidence_ids: List[str] = Field(default_factory=list)


class ValidationReport(BaseModel):
    """
    Consolidated validation report for a product entity across all validation tiers.
    """
    product_id: str
    passed: bool
    status: str
    total_rules_checked: int
    passed_count: int
    failed_count: int
    conflict_count: int
    results: List[ValidationResultItem] = Field(default_factory=list)
    conflicts: List[CrossSourceComparisonResult] = Field(default_factory=list)
