"""
Heuristic manufacturer and brand alias mappings derived from input dataset observation.
NOTE: These are deterministic heuristic rules (HEURISTIC) and NOT official UniHack/Unilog reference data.
Official reference spreadsheets (Unicat_Manufacturer_and_Brand_List.xlsx) are UNAVAILABLE.
"""

from typing import Dict, Tuple

# lowercase alias -> (canonical_name, canonical_code)
MANUFACTURER_ALIASES: Dict[str, Tuple[str, str]] = {
    "freud inc": ("Freud", "2435"),
    "freud": ("Freud", "2435"),
    "mirka abrasives inc": ("Mirka", "MIRUS"),
    "mirka": ("Mirka", "MIRUS"),
    "jam industrial supply llc": ("Jam Industrial Supply", "JAMIN"),
    "jam industrial supply": ("Jam Industrial Supply", "JAMIN"),
    "milwaukee accessory": ("Milwaukee", "4031"),
    "milwaukee": ("Milwaukee", "4031"),
    "3 m co": ("3M", "5293"),
    "3m": ("3M", "5293"),
    "phillips lighting": ("Philips Lighting", "5831"),
    "philips": ("Philips Lighting", "5831"),
    "boise cascade building materials": ("Boise Cascade", "BOICA"),
    "boise cascade": ("Boise Cascade", "BOICA"),
    "appliance dealers cooperative": ("Appliance Dealers Cooperative", "APPDE"),
    "kichler lighting": ("Kichler", "KICLI"),
    "kichler": ("Kichler", "KICLI"),
    "parksite": ("Parksite", "6151"),
    "black & decker/dewlt": ("Black & Decker", "2585"),
    "black & decker": ("Black & Decker", "2585"),
    "dewalt": ("DeWalt", "2585"),
    "u s lumber": ("US Lumber", "3073"),
    "satco prod inc": ("Satco", "5573"),
    "satco": ("Satco", "5573"),
    "makita usa inc": ("Makita", "5142"),
    "makita": ("Makita", "5142"),
    "southwire/g turner": ("Southwire", "6603"),
    "southwire": ("Southwire", "6603"),
    "leviton mfg co": ("Leviton", "4927"),
    "leviton": ("Leviton", "4927"),
    "festool usa": ("Festool", "FESTO"),
    "festool": ("Festool", "FESTO"),
    "kreg tool company": ("Kreg", "KRETO"),
    "edge eyewear inc": ("Edge Eyewear", "EDGSA"),
    "tech gear 5.7 inc": ("Tech Gear 5.7", "TECGE"),
    "tech gear 5.7": ("Tech Gear 5.7", "TECGE"),
    "tech gear": ("Tech Gear 5.7", "TECGE"),
    "u s tape company": ("US Tape", "6694"),
    "palmer donavin mfg company": ("Palmer Donavin", "PALDO"),
    "hunter fan co": ("Hunter Fan", "4381"),
    "premier metals": ("Premier Metals", "PREME"),
    "vessel tools usa inc": ("Vessel Tools", "VESTO"),
    "oliver machinery company": ("Oliver Machinery", "OLIMA"),
    "prime wire & cable": ("Prime Wire & Cable", "3562"),
    "bow products": ("Bow Products", "BOWPR"),
    "saw stop llc": ("SawStop", "SAWST"),
    "rees cast stone company": ("Rees Cast Stone", "REECA"),
    "united window & door manufacturing": ("United Window & Door", "UNIWI"),
    "westwood lumber sales": ("Westwood Lumber", "WESLU"),
    "woodpeckers inc": ("Woodpeckers", "WOODP"),
    "robt bosch tool corp": ("Bosch", "6564"),
    "bosch": ("Bosch", "6564"),
    "velux america inc": ("Velux", "VELAM"),
    "fenton bros electric inc": ("Fenton Bros Electric", "FENBR"),
    "square d con prod dv": ("Square D", "6825"),
    "square d": ("Square D", "6825"),
    "whiteside machine & repair co": ("Whiteside Machine", "WHIMA"),
    "cmt usa inc": ("CMT", "CMTUS"),
    "jpw industries": ("JPW Industries", "JPWIN"),
    "wera tools na inc": ("Wera", "WERTO"),
    "provia": ("ProVia", "PRODO"),
    "certainteed gypsum": ("CertainTeed", "2765"),
    "hager hinge co": ("Hager", "4189"),
    "cooper lighting": ("Cooper Lighting", "7638"),
    "feit electric": ("Feit Electric", "3468"),
    "acg brands": ("ACG Brands", "1154"),
    "senco products inc": ("Senco", "4650"),
    "national nail corp": ("National Nail", "7439"),
    "prebena": ("Prebena", "PREBE"),
    "marshalltown trowel": ("Marshalltown", "5155"),
    "ohio firewatch protection inc": ("Ohio Firewatch Protection", "HOLFS"),
    "first alert - b r k brands": ("First Alert", "2754"),
    "malco prod": ("Malco", "2370"),
    "king canada inc": ("King Canada", "KINCA"),
    "woodstock intl": ("Woodstock International", "3658"),
    "emseal joint systems ltd": ("Emseal", "EMSJO"),
    "v & v appliance parts inc": ("V&V Appliance Parts", "VVAPP"),
    "a j manufacturing inc": ("AJ Manufacturing", "AJMAN"),
    "huber eng wood llc": ("Huber Engineered Wood", "3158"),
    "millertech energy solutions": ("MillerTech", "MILTE"),
    "metalmark industrial inc": ("Metalmark Industrial", "METIN"),
    "thomas & betts": ("Thomas & Betts", "7405"),
    "cooper wiring devices": ("Cooper Wiring Devices", "3560"),
    "lithonia lighting": ("Lithonia Lighting", "2776"),
    "keystone": ("Keystone", "5702"),
    "maxsa innovations": ("Maxsa Innovations", "MAXIN"),
    "streamlight": ("Streamlight", "7277"),
    "police security": ("Police Security", "9470"),
    "woods wire southwire": ("Woods Wire", "7579"),
    "sabre": ("Sabre", "9195"),
    "radians": ("Radians", "7363"),
    "amana tool corp": ("Amana Tool", "AMATO"),
    "irwin industrial tools": ("Irwin", "5863"),
    "j&g machinery": ("J&G Machinery", "JGMAC"),
    "siemens": ("Siemens", ""),
    "abb": ("ABB", ""),
    "schneider electric": ("Schneider Electric", ""),
    "eaton": ("Eaton", ""),
    "ge": ("GE", ""),
    "general electric": ("GE", ""),
    "lg": ("LG", ""),
    "whirlpool": ("Whirlpool", ""),
    "kitchen aid": ("KitchenAid", ""),
    "kitchenaid": ("KitchenAid", ""),
}

BRAND_ALIASES: Dict[str, str] = {
    "diablo": "Diablo",
    "3m": "3M",
    "milw": "Milwaukee",
    "milwaukee": "Milwaukee",
    "ge": "GE",
    "lg": "LG",
    "whirlpool": "Whirlpool",
    "kitchen aid": "KitchenAid",
    "kitchenaid": "KitchenAid",
    "maytag": "Maytag",
    "speed queen": "Speed Queen",
    "sq": "Speed Queen",
    "cafe": "Café",
    "café": "Café",
    "frigidaire": "Frigidaire",
    "kichler": "Kichler",
    "trex": "Trex",
    "timbertech": "TimberTech",
    "timber tech": "TimberTech",
    "azek": "Azek",
    "freud": "Freud",
    "mirka": "Mirka",
    "bosch": "Bosch",
    "dewalt": "DeWalt",
    "makita": "Makita",
    "festool": "Festool",
    "leviton": "Leviton",
    "philips": "Philips",
    "feit": "Feit Electric",
    "feit electric": "Feit Electric",
    "lithonia": "Lithonia",
    "lithonia lighting": "Lithonia",
    "satco": "Satco",
    "nuvo": "Nuvo",
    "hunter": "Hunter Fan",
    "hunter fan": "Hunter Fan",
    "siemens": "Siemens",
    "abb": "ABB",
    "schneider": "Schneider Electric",
    "schneider electric": "Schneider Electric",
    "eaton": "Eaton",
    "hiolit": "Hiolit",
    "abranet": "Abranet",
    "cubitron": "Cubitron",
    "emseal": "Emseal",
    "wera": "Wera",
    "rdi": "RDI",
    "finyline": "Finyl Line",
    "finyl line": "Finyl Line",
    "heritage": "Heritage",
    "locknlube": "LockNLube",
    "lnl": "LockNLube",
    "rees cast stone": "Rees Cast Stone",
    "boise cascade": "Boise Cascade",
    "lp smartside": "LP SmartSide",
    "dsi westbury": "DSI Westbury",
    "james hardie": "James Hardie",
    "hardie": "James Hardie",
    "provia": "ProVia",
    "certainteed": "CertainTeed",
    "hager": "Hager",
    "senco": "Senco",
    "national nail": "National Nail",
    "prebena": "Prebena",
    "marshalltown": "Marshalltown",
    "first alert": "First Alert",
    "malco": "Malco",
    "king canada": "King Canada",
    "woodstock": "Woodstock International",
    "millertech": "MillerTech",
    "metalmark": "Metalmark Industrial",
    "thomas & betts": "Thomas & Betts",
    "maxsa": "Maxsa Innovations",
    "streamlight": "Streamlight",
    "police security": "Police Security",
    "sabre": "Sabre",
    "radians": "Radians",
    "amana tool": "Amana Tool",
    "irwin": "Irwin",
    "jg machinery": "J&G Machinery",
    "square d": "Square D",
    "velux": "Velux",
    "fenton bros": "Fenton Bros",
    "cooper": "Cooper Lighting",
    "southwire": "Southwire",
    "prime": "Prime Wire & Cable",
    "kreg": "Kreg",
    "vessel": "Vessel Tools",
    "bow": "Bow Products",
    "sawstop": "SawStop",
    "woodpeckers": "Woodpeckers",
    "cmt": "CMT",
    "whiteside": "Whiteside Machine",
    "jpw": "JPW Industries",
    "owens corning": "Owens Corning",
    "henry": "Henry",
    "zip system": "Huber Engineered Wood",
}
